version: '3.1'
services:
  my_cooking:
    build: .
    image: my-cooking-book
    container_name: my-cooking-book
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - Stat_URL=jdbc:postgresql://my-cooking-db:5432/my_cooking_book
      - Stat_USER=postgres
      - Stat_PASSWORD=root

  db:
    image: postgres:14-alpine
    build:
      context: ./
      dockerfile: ./Dockerfile.postgres
    container_name: my-cooking-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=my_cooking_book
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root