drop table IF EXISTS users CASCADE;
drop table IF EXISTS authorities CASCADE;

CREATE TABLE IF NOT EXISTS users(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                      first_name varchar(50),
                      username varchar(50) not null ,
                      password varchar(249) not null ,
                      email varchar(50),
                      phone_number varchar(50),
                      enabled boolean,
                      primary key (username)
);

CREATE TABLE IF NOT EXISTS authorities (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                             username varchar not null,
                             authority varchar(50) not null,
                             constraint fk_authorities_users foreign key(username) references users(username)
);
